Feature/clear command
inkdevhub/swanky-cli pull request #189
Opened 2023-11-01 08:18 UTC by Juminstock

Added clear command and documentation.

2023-11-01 10:44 UTC, codespool commented on .github/ISSUE_TEMPLATE/backlog-ticket.md
No need to edit the template, it's meant to be copied to the PR description.

2023-11-01 10:44 UTC, codespool commented on src/commands/clear/index.ts
> +    const spinner = new Spinner();
there's a `spinner` instance in the parent class already.

2023-11-01 10:44 UTC, codespool commented on src/commands/clear/index.ts
> +        `Error while to delete the folder ${path}: ${err}Error while to delete the folder ${path}: ${err}`
Why the repetition?
When rethrowing, the orginal error can be included as a second arguement's `cause` property.
`throw new FileError("Error deleting the folder ${path}.", {cause: err})`

2023-11-01 10:44 UTC, codespool commented on src/commands/clear/index.ts
> +  static async deleteFolder(path: string): Promise<void> {
Does this need to be static? What's the benefit? If it's meant to be used by other classes, it should be a part of `lib`

2023-11-01 10:44 UTC, codespool commented on src/commands/clear/index.ts
> +import { flagUsage } from "@oclif/core/lib/parser/help.js";
Where is this used?

2023-11-01 10:44 UTC, codespool commented on src/commands/clear/index.ts
> +    }
Checking only for `args.contractName === undefined && !flags.all` would cover the use case (if --all is passed, just ignore the arg)

2023-11-01 10:44 UTC, codespool commented on src/commands/clear/index.ts
> +      foldersToDelete.map(async (folder) => {
Don't use `.map()` if you're not expecting a return. (use forEach() in that case)

2023-11-01 10:44 UTC, codespool commented on src/commands/clear/index.ts
> +      if (fs.existsSync(folder.path)) {
`fs-extra`'s `.remove()` method doesn't need this check.

2023-11-01 10:44 UTC, codespool commented on src/commands/clear/index.ts
> +        await Clear.deleteFolder(folder.path)
the `this.spiner` instance has a `.runCommand()` for this use

2023-11-02 03:18 UTC, Juminstock commented
Thanks for the feedback, Codespool. The PR has been updated based on your comments.

2024-02-15 17:10 UTC, ipapandinas requested changes
sorry for the late response @Juminstock, your implementation of the `clear` command looks pretty solid, thank you for contributing!

I added some comments for small code structure adjustments; once implemented I will approve this PR

2024-02-15 17:10 UTC, ipapandinas commented on src/commands/clear/index.ts
> +        let resultSpinner = await this.spinner.runCommand( async () => this.deleteFolder(folder.path),
The variable `resultSpinner` is useless, no need to store the command result.

2024-02-15 17:10 UTC, ipapandinas commented on src/commands/clear/index.ts
> +      for await (const folder of foldersToDelete) {
`await` is useless in the for loop declaration, is already perform at the spinner command level

2024-02-15 17:10 UTC, ipapandinas commented on src/commands/clear/index.ts
> +    if(args.contractName === undefined && !flags.all) throw new ConfigError("You need to send any flag or argument.")
The config error message can be more explicit, something like: "Specify a contract name or use the --all flag to delete all artifacts."

2024-02-15 17:10 UTC, ipapandinas commented on src/commands/clear/index.ts
> +      foldersToDelete.push({
No need to push, a direct `foldersToDelete` assignment works well:

```typescript
foldersToDelete = [
  { name: "Artifacts", path: path.join(workDirectory, './artifacts') },
  { name: "Target", path: path.join(workDirectory, './target') }
];
```

2024-02-15 17:10 UTC, ipapandinas commented on src/commands/clear/index.ts
> +      foldersToDelete.push({
Same here, you can make a direct `foldersToDelete` assignment too.

2024-02-25 06:51 UTC, Juminstock commented
Hi @ipapandinas, thank you for your comments in the code. I've resolved the bugs and improve the code based on your tips!

2024-02-26 10:21 UTC, ipapandinas approved these changes
LGTM, thank you for your contribution @Juminstock 🙌
It will be include in the upcoming new release completing the [ink-devhub-1](https://github.com/inkdevhub/swanky-cli/tree/ink-devhub-1) proposal.

2024-03-12 16:23 UTC, merged